rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.spinach
  - gemfiles/Gemfile.minitest
  - gemfiles/Gemfile.test-unit
  - gemfiles/Gemfile.cucumber
  - gemfiles/Gemfile.rspec

matrix:
  exclude:
    - rvm: jruby
      gemfile: gemfiles/Gemfile.spinach

branches:
  only:
    - master
